[package]
name = "srp"
version = "0.1.0"
authors = ["Michael Micucci <michael.micucci@exchange.co.jp>"]

[dependencies]
base64 = "*"
log = "0.3"
hmac = "0.5.0"
hex = "*"
md5 = "*"
num-bigint = "0.2"
rand = "0.5"
rustc-serialize = "0.3"
sha2 = "*"
